package org.flowgrid.model;

/**
 * Created by haustein on 18.10.15.
 */
public enum Shape {
  AND, ASYNC, BAR, BRANCH, CIRCLE, HEXAGON, RECTANGLE, INPUT, INPUT_OUTPUT, NONE, NOT,
  OUTPUT, OR, OVAL, FOLDER, PACKAGE, PARALLELOGRAM, RHOMBUS, ROUNDED_RECTANGLE,
  STAR, STORAGE, TRAPEZOID_UP, TRAPEZOID_DOWN, XOR, SQUARE, SOUND
}
